rejection_reasons:
  population:
    - code: "P1"
      description: "P: Not population of interest"

  intervention_exposure:
    - code: "IE1"
      description: "I/E: Not intervention/exposure of interest"

  outcome:
    - code: "O1"
      description: "O: No outcome of interest"

  study_design:
    - code: "SD1"
      description: "D: Not study design of interest"
    - code: "SD2"
      description: "D: Follow-up duration too short"

  setting:
    - code: "S1"
      description: "S: Not setting of interest"

  sample_size:
    - code: "N1"
      description: "N: N analyzed too small"
